/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoLayoutRouteRouteImport } from './routes/_demoLayout/route'
import { Route as AppLayoutRouteRouteImport } from './routes/_appLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TancnLayoutOrderRouteImport } from './routes/_tancnLayout/order'
import { Route as DemoLayoutDemoIndexRouteImport } from './routes/_demoLayout/demo/index'
import { Route as AppLayoutAppIndexRouteImport } from './routes/_appLayout/app/index'
import { Route as DemoLayoutDemoTanstackQueryRouteImport } from './routes/_demoLayout/demo/tanstack-query'
import { Route as DemoLayoutDemoTableRouteImport } from './routes/_demoLayout/demo/table'
import { Route as DemoLayoutDemoStorybookRouteImport } from './routes/_demoLayout/demo/storybook'
import { Route as DemoLayoutDemoStoreRouteImport } from './routes/_demoLayout/demo/store'
import { Route as DemoLayoutDemoPrismaRouteImport } from './routes/_demoLayout/demo/prisma'
import { Route as DemoLayoutDemoClerkRouteImport } from './routes/_demoLayout/demo/clerk'
import { Route as DemoLayoutDemoStartServerFuncsRouteImport } from './routes/_demoLayout/demo/start.server-funcs'
import { Route as DemoLayoutDemoStartApiRequestRouteImport } from './routes/_demoLayout/demo/start.api-request'
import { Route as DemoLayoutDemoFormSimpleRouteImport } from './routes/_demoLayout/demo/form.simple'
import { Route as DemoLayoutDemoFormAddressRouteImport } from './routes/_demoLayout/demo/form.address'
import { Route as DemoLayoutDemoApiTqTodosRouteImport } from './routes/_demoLayout/demo/api.tq-todos'
import { Route as DemoLayoutDemoApiNamesRouteImport } from './routes/_demoLayout/demo/api.names'
import { Route as DemoLayoutDemoStartSsrIndexRouteImport } from './routes/_demoLayout/demo/start.ssr.index'
import { Route as DemoLayoutDemoStartSsrSpaModeRouteImport } from './routes/_demoLayout/demo/start.ssr.spa-mode'
import { Route as DemoLayoutDemoStartSsrFullSsrRouteImport } from './routes/_demoLayout/demo/start.ssr.full-ssr'
import { Route as DemoLayoutDemoStartSsrDataOnlyRouteImport } from './routes/_demoLayout/demo/start.ssr.data-only'

const DemoLayoutRouteRoute = DemoLayoutRouteRouteImport.update({
  id: '/_demoLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TancnLayoutOrderRoute = TancnLayoutOrderRouteImport.update({
  id: '/_tancnLayout/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutDemoIndexRoute = DemoLayoutDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const AppLayoutAppIndexRoute = AppLayoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const DemoLayoutDemoTanstackQueryRoute =
  DemoLayoutDemoTanstackQueryRouteImport.update({
    id: '/demo/tanstack-query',
    path: '/demo/tanstack-query',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoTableRoute = DemoLayoutDemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const DemoLayoutDemoStorybookRoute = DemoLayoutDemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const DemoLayoutDemoStoreRoute = DemoLayoutDemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const DemoLayoutDemoPrismaRoute = DemoLayoutDemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const DemoLayoutDemoClerkRoute = DemoLayoutDemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const DemoLayoutDemoStartServerFuncsRoute =
  DemoLayoutDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoStartApiRequestRoute =
  DemoLayoutDemoStartApiRequestRouteImport.update({
    id: '/demo/start/api-request',
    path: '/demo/start/api-request',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoFormSimpleRoute =
  DemoLayoutDemoFormSimpleRouteImport.update({
    id: '/demo/form/simple',
    path: '/demo/form/simple',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoFormAddressRoute =
  DemoLayoutDemoFormAddressRouteImport.update({
    id: '/demo/form/address',
    path: '/demo/form/address',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoApiTqTodosRoute =
  DemoLayoutDemoApiTqTodosRouteImport.update({
    id: '/demo/api/tq-todos',
    path: '/demo/api/tq-todos',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoApiNamesRoute = DemoLayoutDemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => DemoLayoutRouteRoute,
} as any)
const DemoLayoutDemoStartSsrIndexRoute =
  DemoLayoutDemoStartSsrIndexRouteImport.update({
    id: '/demo/start/ssr/',
    path: '/demo/start/ssr/',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoStartSsrSpaModeRoute =
  DemoLayoutDemoStartSsrSpaModeRouteImport.update({
    id: '/demo/start/ssr/spa-mode',
    path: '/demo/start/ssr/spa-mode',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoStartSsrFullSsrRoute =
  DemoLayoutDemoStartSsrFullSsrRouteImport.update({
    id: '/demo/start/ssr/full-ssr',
    path: '/demo/start/ssr/full-ssr',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)
const DemoLayoutDemoStartSsrDataOnlyRoute =
  DemoLayoutDemoStartSsrDataOnlyRouteImport.update({
    id: '/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => DemoLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof TancnLayoutOrderRoute
  '/demo/clerk': typeof DemoLayoutDemoClerkRoute
  '/demo/prisma': typeof DemoLayoutDemoPrismaRoute
  '/demo/store': typeof DemoLayoutDemoStoreRoute
  '/demo/storybook': typeof DemoLayoutDemoStorybookRoute
  '/demo/table': typeof DemoLayoutDemoTableRoute
  '/demo/tanstack-query': typeof DemoLayoutDemoTanstackQueryRoute
  '/app': typeof AppLayoutAppIndexRoute
  '/demo': typeof DemoLayoutDemoIndexRoute
  '/demo/api/names': typeof DemoLayoutDemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoLayoutDemoApiTqTodosRoute
  '/demo/form/address': typeof DemoLayoutDemoFormAddressRoute
  '/demo/form/simple': typeof DemoLayoutDemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoLayoutDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoLayoutDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoLayoutDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoLayoutDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoLayoutDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoLayoutDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof TancnLayoutOrderRoute
  '/demo/clerk': typeof DemoLayoutDemoClerkRoute
  '/demo/prisma': typeof DemoLayoutDemoPrismaRoute
  '/demo/store': typeof DemoLayoutDemoStoreRoute
  '/demo/storybook': typeof DemoLayoutDemoStorybookRoute
  '/demo/table': typeof DemoLayoutDemoTableRoute
  '/demo/tanstack-query': typeof DemoLayoutDemoTanstackQueryRoute
  '/app': typeof AppLayoutAppIndexRoute
  '/demo': typeof DemoLayoutDemoIndexRoute
  '/demo/api/names': typeof DemoLayoutDemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoLayoutDemoApiTqTodosRoute
  '/demo/form/address': typeof DemoLayoutDemoFormAddressRoute
  '/demo/form/simple': typeof DemoLayoutDemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoLayoutDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoLayoutDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoLayoutDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoLayoutDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoLayoutDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoLayoutDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_appLayout': typeof AppLayoutRouteRouteWithChildren
  '/_demoLayout': typeof DemoLayoutRouteRouteWithChildren
  '/_tancnLayout/order': typeof TancnLayoutOrderRoute
  '/_demoLayout/demo/clerk': typeof DemoLayoutDemoClerkRoute
  '/_demoLayout/demo/prisma': typeof DemoLayoutDemoPrismaRoute
  '/_demoLayout/demo/store': typeof DemoLayoutDemoStoreRoute
  '/_demoLayout/demo/storybook': typeof DemoLayoutDemoStorybookRoute
  '/_demoLayout/demo/table': typeof DemoLayoutDemoTableRoute
  '/_demoLayout/demo/tanstack-query': typeof DemoLayoutDemoTanstackQueryRoute
  '/_appLayout/app/': typeof AppLayoutAppIndexRoute
  '/_demoLayout/demo/': typeof DemoLayoutDemoIndexRoute
  '/_demoLayout/demo/api/names': typeof DemoLayoutDemoApiNamesRoute
  '/_demoLayout/demo/api/tq-todos': typeof DemoLayoutDemoApiTqTodosRoute
  '/_demoLayout/demo/form/address': typeof DemoLayoutDemoFormAddressRoute
  '/_demoLayout/demo/form/simple': typeof DemoLayoutDemoFormSimpleRoute
  '/_demoLayout/demo/start/api-request': typeof DemoLayoutDemoStartApiRequestRoute
  '/_demoLayout/demo/start/server-funcs': typeof DemoLayoutDemoStartServerFuncsRoute
  '/_demoLayout/demo/start/ssr/data-only': typeof DemoLayoutDemoStartSsrDataOnlyRoute
  '/_demoLayout/demo/start/ssr/full-ssr': typeof DemoLayoutDemoStartSsrFullSsrRoute
  '/_demoLayout/demo/start/ssr/spa-mode': typeof DemoLayoutDemoStartSsrSpaModeRoute
  '/_demoLayout/demo/start/ssr/': typeof DemoLayoutDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/demo/clerk'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/app'
    | '/demo'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order'
    | '/demo/clerk'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/app'
    | '/demo'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/_appLayout'
    | '/_demoLayout'
    | '/_tancnLayout/order'
    | '/_demoLayout/demo/clerk'
    | '/_demoLayout/demo/prisma'
    | '/_demoLayout/demo/store'
    | '/_demoLayout/demo/storybook'
    | '/_demoLayout/demo/table'
    | '/_demoLayout/demo/tanstack-query'
    | '/_appLayout/app/'
    | '/_demoLayout/demo/'
    | '/_demoLayout/demo/api/names'
    | '/_demoLayout/demo/api/tq-todos'
    | '/_demoLayout/demo/form/address'
    | '/_demoLayout/demo/form/simple'
    | '/_demoLayout/demo/start/api-request'
    | '/_demoLayout/demo/start/server-funcs'
    | '/_demoLayout/demo/start/ssr/data-only'
    | '/_demoLayout/demo/start/ssr/full-ssr'
    | '/_demoLayout/demo/start/ssr/spa-mode'
    | '/_demoLayout/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren
  DemoLayoutRouteRoute: typeof DemoLayoutRouteRouteWithChildren
  TancnLayoutOrderRoute: typeof TancnLayoutOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_demoLayout': {
      id: '/_demoLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DemoLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tancnLayout/order': {
      id: '/_tancnLayout/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof TancnLayoutOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demoLayout/demo/': {
      id: '/_demoLayout/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoLayoutDemoIndexRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_appLayout/app/': {
      id: '/_appLayout/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutAppIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_demoLayout/demo/tanstack-query': {
      id: '/_demoLayout/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoLayoutDemoTanstackQueryRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/table': {
      id: '/_demoLayout/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoLayoutDemoTableRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/storybook': {
      id: '/_demoLayout/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoLayoutDemoStorybookRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/store': {
      id: '/_demoLayout/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoLayoutDemoStoreRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/prisma': {
      id: '/_demoLayout/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoLayoutDemoPrismaRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/clerk': {
      id: '/_demoLayout/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoLayoutDemoClerkRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/start/server-funcs': {
      id: '/_demoLayout/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoLayoutDemoStartServerFuncsRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/start/api-request': {
      id: '/_demoLayout/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoLayoutDemoStartApiRequestRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/form/simple': {
      id: '/_demoLayout/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoLayoutDemoFormSimpleRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/form/address': {
      id: '/_demoLayout/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoLayoutDemoFormAddressRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/api/tq-todos': {
      id: '/_demoLayout/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoLayoutDemoApiTqTodosRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/api/names': {
      id: '/_demoLayout/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoLayoutDemoApiNamesRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/start/ssr/': {
      id: '/_demoLayout/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoLayoutDemoStartSsrIndexRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/start/ssr/spa-mode': {
      id: '/_demoLayout/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoLayoutDemoStartSsrSpaModeRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/start/ssr/full-ssr': {
      id: '/_demoLayout/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoLayoutDemoStartSsrFullSsrRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
    '/_demoLayout/demo/start/ssr/data-only': {
      id: '/_demoLayout/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoLayoutDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof DemoLayoutRouteRoute
    }
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutAppIndexRoute: typeof AppLayoutAppIndexRoute
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutAppIndexRoute: AppLayoutAppIndexRoute,
}

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
)

interface DemoLayoutRouteRouteChildren {
  DemoLayoutDemoClerkRoute: typeof DemoLayoutDemoClerkRoute
  DemoLayoutDemoPrismaRoute: typeof DemoLayoutDemoPrismaRoute
  DemoLayoutDemoStoreRoute: typeof DemoLayoutDemoStoreRoute
  DemoLayoutDemoStorybookRoute: typeof DemoLayoutDemoStorybookRoute
  DemoLayoutDemoTableRoute: typeof DemoLayoutDemoTableRoute
  DemoLayoutDemoTanstackQueryRoute: typeof DemoLayoutDemoTanstackQueryRoute
  DemoLayoutDemoIndexRoute: typeof DemoLayoutDemoIndexRoute
  DemoLayoutDemoApiNamesRoute: typeof DemoLayoutDemoApiNamesRoute
  DemoLayoutDemoApiTqTodosRoute: typeof DemoLayoutDemoApiTqTodosRoute
  DemoLayoutDemoFormAddressRoute: typeof DemoLayoutDemoFormAddressRoute
  DemoLayoutDemoFormSimpleRoute: typeof DemoLayoutDemoFormSimpleRoute
  DemoLayoutDemoStartApiRequestRoute: typeof DemoLayoutDemoStartApiRequestRoute
  DemoLayoutDemoStartServerFuncsRoute: typeof DemoLayoutDemoStartServerFuncsRoute
  DemoLayoutDemoStartSsrDataOnlyRoute: typeof DemoLayoutDemoStartSsrDataOnlyRoute
  DemoLayoutDemoStartSsrFullSsrRoute: typeof DemoLayoutDemoStartSsrFullSsrRoute
  DemoLayoutDemoStartSsrSpaModeRoute: typeof DemoLayoutDemoStartSsrSpaModeRoute
  DemoLayoutDemoStartSsrIndexRoute: typeof DemoLayoutDemoStartSsrIndexRoute
}

const DemoLayoutRouteRouteChildren: DemoLayoutRouteRouteChildren = {
  DemoLayoutDemoClerkRoute: DemoLayoutDemoClerkRoute,
  DemoLayoutDemoPrismaRoute: DemoLayoutDemoPrismaRoute,
  DemoLayoutDemoStoreRoute: DemoLayoutDemoStoreRoute,
  DemoLayoutDemoStorybookRoute: DemoLayoutDemoStorybookRoute,
  DemoLayoutDemoTableRoute: DemoLayoutDemoTableRoute,
  DemoLayoutDemoTanstackQueryRoute: DemoLayoutDemoTanstackQueryRoute,
  DemoLayoutDemoIndexRoute: DemoLayoutDemoIndexRoute,
  DemoLayoutDemoApiNamesRoute: DemoLayoutDemoApiNamesRoute,
  DemoLayoutDemoApiTqTodosRoute: DemoLayoutDemoApiTqTodosRoute,
  DemoLayoutDemoFormAddressRoute: DemoLayoutDemoFormAddressRoute,
  DemoLayoutDemoFormSimpleRoute: DemoLayoutDemoFormSimpleRoute,
  DemoLayoutDemoStartApiRequestRoute: DemoLayoutDemoStartApiRequestRoute,
  DemoLayoutDemoStartServerFuncsRoute: DemoLayoutDemoStartServerFuncsRoute,
  DemoLayoutDemoStartSsrDataOnlyRoute: DemoLayoutDemoStartSsrDataOnlyRoute,
  DemoLayoutDemoStartSsrFullSsrRoute: DemoLayoutDemoStartSsrFullSsrRoute,
  DemoLayoutDemoStartSsrSpaModeRoute: DemoLayoutDemoStartSsrSpaModeRoute,
  DemoLayoutDemoStartSsrIndexRoute: DemoLayoutDemoStartSsrIndexRoute,
}

const DemoLayoutRouteRouteWithChildren = DemoLayoutRouteRoute._addFileChildren(
  DemoLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
  DemoLayoutRouteRoute: DemoLayoutRouteRouteWithChildren,
  TancnLayoutOrderRoute: TancnLayoutOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
